# WhatATheme
markdown: kramdown

# URL of the Site
url: 'https://alkemist.github.io'
# Base URL of the Site (i.e., Name of the Repository in which the Site is hosted)
baseurl:

# Title of the Site
title: Alkemist
tagline: A side project
# Description of the Site
description: A side project
# URL of Image of the Site
site-image: /assets/images/cercle-alchimique.jpg
# Keywords of the Site
site-keywords:
# URL for the Image of custom Favicon
favicon-url: /assets/images/favicon.png

heroimage: /assets/images/cercle-alchimique.jpg

# Social Media and Contact
# If you don't want to use any icon, you can leave them blank.
email: alkemist000@gmail.com
twitter_username: alkemist000
github_username:  alkemist

# Google Analytics
google-analytics: G-8SYXMRHFJG

author:
  name: Jérémy ACHAIN
  url: https://jeremy-achain.dev

seo:
  name: Jérémy ACHAIN
  type: BlogPosting

image:
  path: /assets/images/cercle-alchimique.jpg
  height: 100
  width: 100

# Name of the Author
author-name: Alkemist
# URL for the Image of the Author
author-image: /assets/images/avatar_bleu.png
# 60 Words About the Author
author-about: >
  Développeur web freelance spécialisé Symfony et Angular.
  Introverti hypersensible, idéaliste en quête de sens #childfree #TDAH
# URL to the Author's Profile (i.e., Github, Twitter, Stackoverflow, etc)
author-url: https://jeremy-achain.dev

# SASS
sass:
  sass_dir: _sass
  style: compressed

# Build settings
plugins:
  - jekyll-admin
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Permalink
permalink: ":categories/:title/"

# Compress
compress_html:
  clippings: all

# Defaults
defaults:
  -
    scope:
      type: 'posts'
    values:
      layout: post
      post-image: ""
      description: ""
      tags:
        - ""
  -
    scope:
      type: 'pages'
    values:
      layout: page

#admin
jekyll_admin:
  hidden_links: ~
  homepage: "posts"

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - _Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
